### ISSUE TITLE
SFTP/SCP through Bastion

### ISSUE THREAD

**Issue by roybj** [ovh/the-bastion#154]
The Bastion works fine for managing SSH connections. But is there way to manage SFTP/SCP through the bastion ?

**Comment by speed47** [comment]
Yes there is, for [SCP](https://ovh.github.io/the-bastion/plugins/open/scp.html).

Even if all the needed information is in the above documentation of the scp plugin, this should probably get a specific *howto* documentation page with examples. The key takeaways are:

- One should have SSH access through the bastion (via personal or group access) to some host to be able to scp from/to it
- One should **also** have the explicit scp access to this host, via the same way that its SSH access to it (personal or group), those kind of accesses can be added/removed with `--scpup` and `--scpdown` (instead of `--user`) in the `groupAddServer` and `accountAddPersonalAccess` commands
- One must get its personalized scp script by running the `--osh scp` plugin
- Then use scp with the script, `scp -S ~/scriptpath <usual scp commands>`

**Comment by dwydler** [comment]
@speed47 
As i read/understand it correct the solutions is primary for linux workstations.
Do you have a workaround/suggestion for windows workstations?

**Comment by roybj** [comment]
> Yes there is, for [SCP](https://ovh.github.io/the-bastion/plugins/open/scp.html).
> 
> Even if all the needed information is in the above documentation of the scp plugin, this should probably get a specific _howto_ documentation page with examples. The key takeaways are:
> 
> * One should have SSH access through the bastion (via personal or group access) to some host to be able to scp from/to it
> * One should **also** have the explicit scp access to this host, via the same way that its SSH access to it (personal or group), those kind of accesses can be added/removed with `--scpup` and `--scpdown` (instead of `--user`) in the `groupAddServer` and `accountAddPersonalAccess` commands
> * One must get its personalized scp script by running the `--osh scp` plugin
> * Then use scp with the script, `scp -S ~/scriptpath <usual scp commands>`

You're right , I already have checked and SCP works fine from the command line.

**Comment by roybj** [comment]
> @speed47
> As i read/understand it correct the solutions is primary for linux workstations.
> Do you have a workaround/suggestion for windows workstations?

Exactly, I would also like to know if Windows, specially clients like WinSCP are supported or not.

**Comment by speed47** [comment]
Correct, I was explaining this with the command line in mind.
From Windows, it should also work out of the box from WSL (through Ubuntu or any other Linux OS installable under WSL).

Unfortunately I'm not expecting this to work with WinSCP or other similar software, as I see no way of "hooking" into its SSH negociation to handle the bastion stuff under the hood. This is what the `-S` command-line option of `scp` is for, and AFAIK it's not implemented in any Windows GUI apps.

**Comment by speed47** [comment]
This is now [part of the documentation](https://ovh.github.io/the-bastion/using/scp.html).
