### ISSUE TITLE
Question on the clush command

### ISSUE THREAD

**Issue by dbodencnve** [ovh/the-bastion#201]
I want to run a number of commands on remote machines through the bastion and understand I should be using the _clush_ plugin for that. 

When I run the plugin and provide a list of ip addresses of hosts I have access to (double checked with selfListAccesses), it is trying to use my username instead of the one defined for that host when adding it to the bastion. I find no way however to provide the username to be used on the remote machines as part of the _clush_ plugin.

What am I missing?

**Comment by speed47** [comment]
Hello,

This is missing from the `--help` of this plugin, but you can use `--user` and `--port` to specify a user (otherwise, defaults to your account name as you noticed), and the port (otherwise defaults to 22).

There is currrently no way to specify a different user/port for each host of the list, but this is an easy-to-add feature if needed.

**Comment by speed47** [comment]
Side note: if you happen to use `clush` (i.e. the actual [clush](https://clustershell.readthedocs.io/en/latest/tools/clush.html#clush-tool) program), you can configure it to use the bastion when connecting to the remote servers, by setting the `ssh_path` of your clush config to the bastion alias.

I'll document it in the FAQ.
