### ISSUE TITLE
Migrate to a new server

### ISSUE THREAD

**Issue by dwydler** [ovh/the-bastion#304]
Hi Guys,
we want to move our instance of The Bastion to a new server.

Is that basically possible? Can someone tell me the necessary steps?
I couldn't find anything in the documentation.

Regards

**Comment by speed47** [comment]
Yes, this is entirely possible, and you have two ways to do that, depending on your preference:

- If your future old server is still online and functioning, you can configure the new one as a slave node: https://ovh.github.io/the-bastion/installation/advanced.html#clustering-high-availability , this way you can test that it works correctly, that you can connect to your infrastructures and everything, then simply shutdown the old node, and then promote the new one (set `readOnlySlaveMode` in `bastion.conf` from `true` to `false`).

- Otherwise you can simply proceed as if your lost your old node and restore from backup. Of course you must have a recent backup archive. By default, it's done once a day, and kept locally, but it's always better to have it sent to a remote location, obviously, and you might have done that during your original installation, see https://ovh.github.io/the-bastion/installation/advanced.html#configuring-keys-accounts-groups-remote-backup for more information. I have a draft documentation detailing how to restore from backup, I can get that expedited if this option has your preference. :)

**Comment by dwydler** [comment]
Thanks. I decided for option one. It worked as you write.

**Comment by ldelelis** [comment]
Hello! @speed47 sorry for bringing up an old issue. I noticed you mentioned having a draft for backup restoration. Has this been published so far? I've been looking for the documentation, but can't find any mentions of the procedure
