### ISSUE TITLE
Login with user@domain

### ISSUE THREAD

**Issue by hanunes** [ovh/the-bastion#437]
We have some devices that only accept the username with the appended domain (user@domain).

If we try to use this combo, the bastion says "Remote user name 'user@domain' seems invalid".

Unfortunately, I've looked at the device's config, but haven't found a way to change the behavior. Is this something that can be done on the bastion side?

**Comment by speed47** [comment]
Thanks for your report!

The @ is not an allowed character for accounts on Linux/BSD or more generally POSIX systems, which are historically the main targets for the bastion, which is why it's not allowed as a remote user name.

However, if some devices that have an SSH daemon expect this format, this should be doable, we'd however have to check first that this doesn't have side effects, as the @ is usually used for SSH as a separator between the login and the host, as in `ssh user@host`.

What kind of device do you have that accepts such format for users logging in to SSH?

**Comment by hanunes** [comment]
Good afternoon, we have Huawei OLTs that need this format specifically. The idea is not to have the bastion user with an @ at the system level, but just allow the ssh command within the bastion to this host with that format.
