### ISSUE TITLE
Error when installing with ttyrec

### ISSUE THREAD

**Issue by Seyfle** [ovh/the-bastion#473]
Hello,
I'm trying to install the bastion without docker, when I run the command `/opt/bastion/bin/admin/install --new-install` I have the following error `~ [!] Couldn't chown ttyrec directory (Invalid argument)`.

Did I do something wrong ?

Thanks for your reply :).

**Comment by Seyfle** [comment]
Hello Cody,

I'm using Perl v5.30.0.

**Comment by dwydler** [comment]
Which operating system and version do you use?

**Comment by speed47** [comment]
@Seyfle This is as if the accountCreate helper got invalid arguments from the accountCreate plugin, regarding the UID to use, which shouldn't happen. Without more info or debug logs, I can't investigate.

Please enable debug (https://ovh.github.io/the-bastion/administration/configuration/bastion_conf.html?highlight=debug#debug), retry, and post the logs here if you still have the error.

**Comment by speed47** [comment]
Closing as inactive, please reopen with the debug logs if needed :)

**Comment by Hugo1380** [comment]
I had a similar error, I don't know if it was exactly the same error, but for me the problem was that I had installed The Bastion on an unprivileged Proxmox container. After several retries, I tried using a privileged container, which seems to be the solution in my case.

My guess, which needs to be confirmed, is that in unprivileged mode the container cannot create an account if the UUIDs are 99999 and 99998.

I hope this can helps others.
