### ISSUE TITLE
Doesn't seem to be a valid bastion group

### ISSUE THREAD

**Issue by dwydler** [ovh/the-bastion#86]
Good morning Guys,
i ad several groups which i want to delete on my bastion host. Every time i delete a group, it output follow error:
```*** Deleting group 'keysbw-rs-servers' sudoers file `-> [ERR.] keysbw-rs-servers doesn't seem to be a valid bastion group```

Below the complete output from console:
```groupDelete --group sbw-rs-servers
---bastion02----------------------------------------------the-bastion-3.01.01---
=> delete an existing bastion group
--------------------------------------------------------------------------------
~ !!!! WARNING !!!! WARNING !!!! WARNING !!!! WARNING !!!! WARNING !!!!
~ !!!! WARNING !!!! WARNING !!!! WARNING !!!! WARNING !!!! WARNING !!!!
~ !!!! WARNING !!!! WARNING !!!! WARNING !!!! WARNING !!!! WARNING !!!!
~
~ You are about to DELETE a bastion group, to be sure you're not drunk, ~ please type the name of the group you want to delete (won't be echoed):
~
~ Removing /home/allowkeeper/surname.givename/allowed.ip.sbw-rs-servers...
~ Found 1 members, removing them from the group ~ ... removing surname.givename from group keysbw-rs-servers-owner ~ Deleting group keysbw-rs-servers-owner...
~ Found 1 members, removing them from the group ~ ... removing surname.givename from group keysbw-rs-servers-aclkeeper ~ Deleting group keysbw-rs-servers-aclkeeper...
~ Found 1 members, removing them from the group ~ ... removing surname.givename from group keysbw-rs-servers-gatekeeper ~ Deleting group keysbw-rs-servers-gatekeeper...
~ Found 2 members, removing them from the group ~ ... removing allowkeeper from group keysbw-rs-servers ~ ... removing surname.givename from group keysbw-rs-servers ~ Deleting main user of group keysbw-rs-servers...
*** Deleting group 'keysbw-rs-servers' sudoers file `-> [ERR.] keysbw-rs-servers doesn't seem to be a valid bastion group
```

If i try to delete the same group again, it display that the group do not exist.
```~ Group 'keysbw-rs-servers' doesn't exist```

What am I doing wrong? Is it a possibly an error?

Regards,
Daniel

**Comment by speed47** [comment]
Hello Daniel,

The message you're seeing is a little regression introduced by 50c016be100f86812a9b88abcd7f75601f8a14ee; thanks for the report.

In the meantime, you can ignore this message: the group has still been deleted successfully. It only leaves a useless file behind in `/etc/sudoers.d`, but this doesn't have any impact since the group no longer exists. The file will be cleaned up automatically on the next update, as regenerating the sudoers file is part of the process of all upgrades.

The fix is easy and should be up soon. We're also patching the tests to better detect such problems.
